var lang = {
    french: {
        systemname: [
            "Lysen",
            "Zelas",
            "Centra",
            "Vecis",
            "Ivurd",
            "Sentori",
            "Fasis",
            "Luya",
            "Kisae",
            "Gaia"
        ],
        etypes: [
            "Planète",
            "Lune",
            "Soleil",
            "Asteroide",
            "Trou Noir",
            "Vaisseau Alien",
            "Vaisseau Mère Alien",
            "Planète Alien",
        ],
        ttitles: [
            "Comment jouer ?",
            "Exploration",
            "Marché",
            "Technologies",
            "Galaxie",
            "Menu du jeu",
        ],
        ttexts: [
            "<h4>L'objecfif est d'obtenir des ressouces pour ensuite les revendre et ainsi obtenir de nouvelles technologies pour améliorer le rendement</h4><br><br>1. Vous pouvez commencer par lancer une mission d'exploration, pour ainsi gagner des ressources et des <i class='red sort amount up icon'></i>Points d'Exploration(EP)<br><br>2. Vendez vôtre marchandise et gagnez de l'argent !<br><br>3. Créez un drone dans les technologies pour automatiser l'obtention de ressources.<br><br>4. Si vous obtenez assez d'argent et que vous vous trouvez dans le système Gaia, vous pouvez changer de galaxie.",
            "L'exploration est l'objectif principal,<br> vous découvrirez de nouvelles destinations en gagnant des <i class='red sort amount up icon'></i> EP ainsi que des ressources.",
            "Le marché est l'endroit pour vendre vos marchandises et gagner de l'argent.<br> Les prix changent chaque jour et sur chaque système.<br><br>Il y a un code couleur pour indiquer la valeur de chaque ressource:<br>- <span class='rouge'>Très basse</span><br>- <span class='argent'>basse</span><br>- <span class=''>Normale</span><br>- <span class='vert'>Chère</span><br>- <span class='Gold'>Très chère</span>",
            "3 Technologies sont actuellement disponibles.<br>- Un drone qui donnera une certaine quantité de la ressource définie, cela dépend du niveau du drone.<br>- Un module d'Hyperespace qui peut débloquer de nouvelles destinations.<br>- Un module d'Hyperpropulsion qui peut réduire le coût de déplacement vers une autre destination.",
            "<h4>Le système de prestige du jeu</h4><br>En changeant de galaxie vous obtiendrez plus d'espaces pour l'inventaire.<br>Mais ceci augmentera aussi le nombre <i class='red sort amount up icon'></i> d'EP requis pour voyager.<br> Ce système permet aussi de réduire le temps de production du drone.",
            "Il y a aussi un menu qui peut vous servir à exporter/importer vôtre sauvegarde afin de pouvoir y rejouer sur un autre navigateur ou PC.",
        ],
        general: [
            "Type",
            "Description",
            "Coût",
            "Action",
            "Nom",
            "Valeur",
            "Inventaire",
            "Vente",
            "Niveau Actuel",
            "Accès",
            "Requis",
            "Niveau",
            "Hyperespace",
            "Hyperpropulsion",
            "Activé",
            "Désactivé",
        ],
        tabnames: [
            "Exploration",
            "Marché",
            "Hyperespace",
            "Drone",
            "Hyperpropulsion",
            "Galaxie",
        ],
        leftcol: [
            "Localisation",
            "Stats",
            "Inventaire",
        ],
        items: [
            "Thamium9",
            "Cuivre",
            "Cellule d'Énergie",
            "Zinc",
            "Nickel",
            "Fer",
            "Aluminium",
            "Iridium",
            "Or",
            "Platine",
            "Carbone",
            "Plutonium",
            "Heridium",
            "Emeril",
            "Titane",
            "Antimatière",
            "Radnox",
            "Omegon",
            "Rubeum",
            "Cymatygen"
        ],
        buttons: [
            "Entrer dans le Trou Noir",
            "Options & Statistiques",
            "Guide",
            "Contact",
            "Offrir un café ♥",
            "Menu",
            "Exploration",
            "Hangar",
            "Galaxie",
        ],
        exploration: [
            "Explorer",
            "Visiter",
            "Max",
        ],
        drones: [
            "Drone rouillé I",
            "Drone rouillé II",
            "Drone basique I",
            "Drone basique II",
            "Drone basique III",
            "Drone avancé I",
            "Drone avancé II",
            "Drone avancé III",
            "Drone alien I",
            "Drone alien II",
        ],
        combat: [
            "Bas",
            "Moyen",
            "Grave",
            "Critique",
            "ALERTE ! PIRATE DANS LA ZONE.",
            "Niveau de menace",
            "Niveau",
            "Pirate",
            "Vous",
            "Attaquer",
            "Se protéger",
            "Fuite",
        ],
    },
    english: {
        systemname: [
            "Lysen",
            "Zelas",
            "Centra",
            "Vecis",
            "Ivurd",
            "Sentori",
            "Fasis",
            "Luya",
            "Kisae",
            "Gaia"
        ],
        etypes: [
            "Planet",
            "Moon",
            "Sun",
            "Asteroid",
            "Black Hole",
            "Alien Spaceship",
            "Alien Flagship",
            "Alien Planet",
        ],
        ttitles: [
            "How to play ?",
            "Exploration",
            "Market",
            "Technologies",
            "Galaxy",
            "Game Menu",
        ],
        ttexts: [
            "<h4>The objective is to get ressouces then sell them to buy technologies to improve the render</h4><br><br>1. You can start with an exploration mission, you will gain ressources and <i class='red sort amount up icon'></i>Exploration Points(EP)<br><br>2. Sell your merchandises to the space market to gain money.<br><br>3. Create a Drone in the technologies to automate the collection of resources.<br><br>4. If your have the required amount of money and you are in Gaia, you can travel to another galaxy.",
            "The exploration is the main objective,<br> you will discover new locations by gaining <i class='red sort amount up icon'></i> EP and ressources.",
            "The market is the place to sell all your merchandises and get some money,<br> the prices are differents on every system & change every days.<br><br>There is a color code to indicate the values of every ressource:<br>- <span class='rouge'>Very Low</span><br>- <span class='argent'>Low</span><br>- <span class=''>Normal</span><br>- <span class='vert'>High</span><br>- <span class='Gold'>Expensive</span>",
            "3 Technologies are unlockables<br>- A drone that gives a certain amount of the defined item, depending of your current drone level.<br> - An hyperspace module that can unlock new locations.<br>- An hyperdrive module that can reduce the cost to travel to another location.",
            "<h4>The prestige system of the game</h4><br>The galaxy will give you more inventory places.<br>But it will also increase the <i class='red sort amount up icon'></i> EP needed to change your location.<br>This system also reduce the production time for the drone.",
            "There is also a menu where you can export/import or reset your savegame or re-open this guide.<br>Just click on Menu on the upper left corner of the screen.",
        ],
        general: [
            "Type",
            "Description",
            "Cost",
            "Action",
            "Name",
            "Value",
            "Inventory",
            "Sell",
            "Current level",
            "Access",
            "Require",
            "Level",
            "Hyperspace",
            "Hyperdrive",
            "Enabled",
            "Disabled",
        ],
        tabnames: [
            "Exploration",
            "Market",
            "Hyperspace",
            "Drone",
            "Hyperdrive",
            "Galaxy",
        ],
        leftcol: [
            "Location",
            "Stats",
            "Inventory",
        ],
        items: [
            "Thamium9",
            "Copper",
            "Power Cell",
            "Zinc",
            "Nickel",
            "Iron",
            "Aluminium",
            "Iridium",
            "Gold",
            "Platinum",
            "Carbon",
            "Plutonium",
            "Heridium",
            "Emeril",
            "Titanium",
            "Antimatter",
            "Radnox",
            "Omegon",
            "Rubeum",
            "Cymatygen"
        ],
        buttons: [
            "Enter in the Black Hole",
            "Options & Statistics",
            "Guide",
            "Contact",
            "Offer a coffee ♥",
            "Menu",
            "Exploration",
            "Hangar",
            "Galaxy",
        ],
        exploration: [
            "Explore",
            "Visit",
            "Max",
        ],
        drones: [
            "Rusty drone I",
            "Rusty drone II",
            "Basic drone I",
            "Basic drone II",
            "Basic drone III",
            "Advanced drone I",
            "Advanced drone II",
            "Advanced drone III",
            "Alien drone I",
            "Alien drone II",
        ],
        combat: [
            "Low",
            "Moderate",
            "Severe",
            "Critical",
            "ALERT ! PIRATE IN THE AREA.",
            "Threat level",
            "Level",
            "Pirate",
            "You",
            "Attack",
            "Take Cover",
            "Run Away",
        ],
    },
    chinese: {
        systemname: [
            "里森",
            "泽拉斯",
            "琴特拉",
            "维琪斯",
            "伊弗德",
            "森托里",
            "法西",
            "卢亚",
            "吉萨",
            "盖亚"
        ],
        etypes: [
            "星球",
            "月球",
            "太阳",
            "小行星",
            "黑洞",
            "外星人太空船",
            "外星人旗舰",
            "外星人星球",
        ],
        ttitles: [
            "怎么玩 ?",
            "探索",
            "市场",
            "技术",
            "星系",
            "游戏菜单",
        ],
        ttexts: [
            "<h4>我们的目标是获得资源，然后出售它们来购买改善渲染的技术</h4><br><br>您可以从探索任务开始，您将获得资源和 <i class='red sort amount up icon'></i>探索点(EP)<br><br>2. 将您的商品卖给太空市场以赚钱。<br><br>3. 在技术中创建无人机以自动化资源收集。<br><br>4. 如果您有所需的资金，并且在盖亚（Gaia），则可以前往另一个星系。",
            "探索是主要目标，<br> 您将通过获得发现新的位置 <i class='red sort amount up icon'></i> EP 和资源。",
            "市场是出售你所有商品并赚钱的地方，<br> 每个系统的价格都不一样，每天都在变。<br><br>有一个颜色代码来表示每个资源的值:<br>- <span class='rouge'>很低</span><br>- <span class='argent'>低</span><br>- <span class=''>正常</span><br>- <span class='vert'>高</span><br>- <span class='Gold'>昂贵</span>",
            "3 技术是可解锁的<br>- 一架无人机，根据你当前的无人机等级，提供一定数量的已定义物品。<br> - 一个可以解锁新位置的超空间模块。<br>- 一个超光速推进装置模块可以降低成本旅行到另一个位置。",
            "<h4>游戏的声望系统</h4><br>星系会给你更多的库存空间。<br>但它也会增加 <i class='red sort amount up icon'></i> EP需求当你改变位置。<br>该系统还减少了无人机的生产时间。",
            "还有一个菜单，您可以在其中导出/导入或重置您的游戏存档或重新打开本指南。<br>只需点击屏幕左上角的菜单。",
        ],
        general: [
            "类型",
            "描述",
            "成本",
            "操作",
            "名称",
            "价值",
            "库存",
            "出售",
            "当前等级",
            "访问",
            "要求",
            "等级",
            "多维空间",
            "超光速推进装置",
            "启用",
            "禁用",
        ],
        tabnames: [
            "探索",
            "市场",
            "多维空间",
            "无人机",
            "超光速推进装置",
            "星系",
        ],
        leftcol: [
            "位置",
            "属性",
            "库存",
        ],
        items: [
            "钍9",
            "铜",
            "动力电池",
            "锌",
            "镍",
            "铁",
            "铝",
            "铱",
            "黄金",
            "铂",
            "碳",
            "钚",
            "伊迪姆",
            "艾默瑞",
            "钛",
            "反物质",
            "氡",
            "欧米伽",
            "红宝石",
            "胞质原"
        ],
        buttons: [
            "进入黑洞",
            "选项 & 统计",
            "指南",
            "联系",
            "奉献一杯咖啡 ♥",
            "菜单",
            "探索",
            "机库",
            "星系",
        ],
        exploration: [
            "探索",
            "访问",
            "最大",
        ],
        drones: [
            "生锈的无人机 I",
            "生锈的无人机 II",
            "生锈的无人机 I",
            "生锈的无人机 II",
            "生锈的无人机 III",
            "高级无人机 I",
            "高级无人机 II",
            "高级无人机 III",
            "外星人无人机 I",
            "外星人无人机 II",
        ],
        combat: [
            "低",
            "中等",
            "严重",
            "危急",
            "提醒！ 海盗在该地区。",
            "Threat level",
            "等级",
            "海盗",
            "你",
            "攻击",
            "掩护",
            "逃跑",
        ],
    }
};
